version: "3"
services:
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: jwtauth
    volumes:
      - ./db/schema.sql:/docker-entrypoint-initdb.d/schema.sql
